### ISSUE TITLE
Does the Action cause unnecessary workflow runs?

### ISSUE THREAD

**Issue by pauleustice** [brainly/action-autoupdate-branch#8]
Hi, I'm considering using this action but it seems it will cause unnecessary workflow runs without a queuing system.

Am I right in thinking that if there are 2 PRs that need rebasing, one will be auto-merged and the second one will then need to be rebased again after that as a result, running the CI workflow checks again?

In other words:

3 PRs open causes 3 executions of PR workflow
PR1 is merged
PR2 and PR3 are auto-rebased leading to 2 extra executions
PR2 is merged
PR3 has to be rebased and then merged, so 1 extra execution

**Comment by felixfbecker** [comment]
Here's an idea: What if it only updated one branch? Then that PR would get merged, triggering another run, and the next PR can get updated. Just needs to make sure the order is stable and fair (FIFO, not prefer new PRs)

**Comment by Fasosnql** [comment]
@pauleustice @felixfbecker we just released version 2.1.0 where `update-limits` parameter has been announced. You can use it to say how many branches you would like to update in one run - mechanism doesn't count PRs which are not met requirements i.e there is no enough approvals or checks didn't pass - depend of the configuration. 

Example configuration for workflow:
```
jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: autoupdate-branch
        uses: brainly/action-autoupdate-branch@2.0.0
        id: updateBranches
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          requiredApprovals: 1
          requiredPassedChecks: true
          update-limits: 2
```
configuration requires 1 approval and passed checks to update branches, also we would like to update only 2 branches what is specified in `update-limits`. It starts merging from oldest to newest one.

Example logs of execution for:
![image](https://user-images.githubusercontent.com/13320330/143245475-fcbdfd1c-293e-45d9-b887-d51e2ee763ec.png)

Release link to check more details: https://github.com/brainly/action-autoupdate-branch/releases/tag/2.1.0
